"""empty message

Revision ID: 1ca0f1b090d8
Revises: 702291ab8f04
Create Date: 2021-06-27 02:02:10.850329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ca0f1b090d8'
down_revision = '702291ab8f04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('release_date',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('distributor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['distributor_id'], ['distributor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('release_date')
    # ### end Alembic commands ###
