"""empty message

Revision ID: 229af8575015
Revises: 
Create Date: 2021-06-24 22:35:17.394277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '229af8575015'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('distributor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lowres_image_url_format', sa.String(), nullable=True),
    sa.Column('highres_image_url_format', sa.String(), nullable=True),
    sa.Column('series_url_format', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('publisher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('series_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_id')
    )
    op.create_table('release',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('image_id', sa.String(), nullable=False),
    sa.Column('publisher_id', sa.Integer(), nullable=False),
    sa.Column('release_id', sa.String(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=True),
    sa.Column('distributor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['distributor_id'], ['distributor.id'], ),
    sa.ForeignKeyConstraint(['publisher_id'], ['publisher.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('release')
    op.drop_table('series')
    op.drop_table('publisher')
    op.drop_table('distributor')
    # ### end Alembic commands ###
