"""empty message

Revision ID: 702291ab8f04
Revises: 229af8575015
Create Date: 2021-06-27 01:06:16.910820

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '702291ab8f04'
down_revision = '229af8575015'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('distributor', sa.Column('last_release', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('distributor', 'last_release')
    # ### end Alembic commands ###
